/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"

#include "LayoutXMLEditor.h"
#include "LayoutEditorApplication.h"

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (LayoutEditorApplication)
